[phases.setup]
nixPkgs = ['python39', 'gcc']

[phases.install]
cmds = ['python -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app'
